### Random Forest

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv(r'C:\Users\DELL\Downloads\credit_scoring.csv')
df

BUSAGE  DAYSDELQ DEFAULT
0       87         2       N
1       89         2       N
2       90         2       N
3       90         2       N
4      101         2       N
..     ...       ...     ...
95     207        70       Y
96     229        70       Y
97      65        72       Y
98      37        76       Y
99      73        80       Y

[100 rows x 3 columns]

In [4]:
df['DEFAULT'].value_counts()

N    75
Y    25
Name: DEFAULT, dtype: int64

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [18]:
X = df.drop(['DEFAULT'], axis = 1)
y = df['DEFAULT']

In [19]:
X_train,X_test,y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [23]:
dtree = DecisionTreeClassifier(criterion='entropy', )
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f"The accuracy : {round(accuracy_score(y_test, y_pred),4)*100}%")
print(classification_report(y_test, y_pred))

[[19  4]
 [ 0  7]]
The accuracy : 86.67%
              precision    recall  f1-score   support

           N       1.00      0.83      0.90        23
           Y       0.64      1.00      0.78         7

    accuracy                           0.87        30
   macro avg       0.82      0.91      0.84        30
weighted avg       0.92      0.87      0.88        30



In [24]:
rf = RandomForestClassifier(n_estimators=500)

In [25]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500)

In [26]:
y_pred = rf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f"The accuracy : {round(accuracy_score(y_test, y_pred),4)*100}%")
print(classification_report(y_test, y_pred))

[[19  4]
 [ 2  5]]
The accuracy : 80.0%
              precision    recall  f1-score   support

           N       0.90      0.83      0.86        23
           Y       0.56      0.71      0.63         7

    accuracy                           0.80        30
   macro avg       0.73      0.77      0.74        30
weighted avg       0.82      0.80      0.81        30



**When RF achieves a lower accuracy than very high DT accuracy, it is a good thing. It tells us that is now less prone to overfitting.**

## Assignment

In this exercise you will work with the Blues Guitarists Hand Posture and Thumbing Style by Region and Birth Period data, which you can download from here Download here. This dataset has 93 entries of various blues guitarists born between 1874 and 1940. Apart from the name of the guitarists, that dataset contains the following four features:

- Regions: 1 means East, 2 means Delta, 3 means Texas.
- Years: 0 for those born before 1906, 1 for the rest
- Hand postures: 1= Extended, 2= Stacked, 3=Lutiform
- Thumb styles: Between 1 and 3, 1=Alternating, 2=Utility, 3=Dead

Using decision tree on this dataset, how accurately you can tell their birth year from their hand postures and thumb styles. 

Given that the birth year is a continuous variable, you could create a discrete variable for classification by doing appropriate segmentations (e.g., 1874-1900: 1, 1901-1920: 2, 1921-1940: 3). How does it affect the evaluation when you include the region while training the model? Now do the same using random forest (on both the above cases) and report the difference.

Make sure to use appropriate training-testing parameters for your evaluation. You should also run the algorithms multiple times, measure various accuracies, and report the average (and perhaps the range).

In [82]:
data = pd.read_csv(r"C:\Users\DELL\Downloads\blues_hand.csv")

In [83]:
data

name state  brthYr  post1906  region  handPost  thumbSty
0        Henry Thomas    TX    1874         0       3         1         3
1        Frank Stokes    TN    1887         0       2         1         3
2         Sam Collins    MS    1887         0       2         1         2
3      Peg Leg Howell    GA    1888         0       1         2         2
4    Huddie Ledbetter    TX    1888         0       3         2         3
..                ...   ...     ...       ...     ...       ...       ...
88  Jimmie Lee Harris    AL    1935         1       2         2         3
89      Snooks Eaglin    LA    1936         1       2         1         2
90      Larry Johnson    GA    1938         1       1         1         1
91        Tom Winslow    NC    1938         1       1         1         1
92      Rober Belfour    MS    1940         1       2         2         2

[93 rows x 7 columns]

In [84]:
data['birth_seg'] = 0

data.loc[(data['brthYr'] >=1874) & (data['brthYr'] <=1900), 'birth_seg'] = 1
data.loc[(data['brthYr'] >1900) & (data['brthYr'] <=1920), 'birth_seg'] = 2
data.loc[(data['brthYr'] >1920) & (data['brthYr']<=1940), 'birth_seg'] = 3


In [86]:
data

name state  brthYr  post1906  region  handPost  thumbSty  \
0        Henry Thomas    TX    1874         0       3         1         3   
1        Frank Stokes    TN    1887         0       2         1         3   
2         Sam Collins    MS    1887         0       2         1         2   
3      Peg Leg Howell    GA    1888         0       1         2         2   
4    Huddie Ledbetter    TX    1888         0       3         2         3   
..                ...   ...     ...       ...     ...       ...       ...   
88  Jimmie Lee Harris    AL    1935         1       2         2         3   
89      Snooks Eaglin    LA    1936         1       2         1         2   
90      Larry Johnson    GA    1938         1       1         1         1   
91        Tom Winslow    NC    1938         1       1         1         1   
92      Rober Belfour    MS    1940         1       2         2         2   

    birth_seg  
0           1  
1           1  
2           1  
3           1  
4           1  
..        ...  
88          3  
89          3  
90          3  
91          3  
92          3  

[93 rows x 8 columns]

In [87]:
data.columns

Index(['name', 'state', 'brthYr', 'post1906', 'region', 'handPost', 'thumbSty',
       'birth_seg'],
      dtype='object')

In [100]:
X = data.drop(['brthYr', 'birth_seg'], axis = 1)
y = data['birth_seg']
X_train, X_test, y_train, y_test = train_test_split(X[['post1906', 'thumbSty']],y, test_size=0.3, random_state=32)

In [101]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import tree

In [102]:
dtree = DecisionTreeClassifier(criterion = 'entropy')
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f"The accuracy : {round(accuracy_score(y_test, y_pred),4)*100}%")
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 7  7  0]
 [ 0  4  0]]
The accuracy : 60.709999999999994%
              precision    recall  f1-score   support

           1       0.59      1.00      0.74        10
           2       0.64      0.50      0.56        14
           3       0.00      0.00      0.00         4

    accuracy                           0.61        28
   macro avg       0.41      0.50      0.43        28
weighted avg       0.53      0.61      0.54        28



C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [93]:
data['birth_seg'].value_counts()

2    51
1    25
3    17
Name: birth_seg, dtype: int64

In [95]:
y_test.values

array([3, 2, 3, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 3, 2, 2, 1, 1, 3, 1,
       2, 1, 1, 2, 2, 2], dtype=int64)

In [96]:
y_pred

array([2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1,
       2, 1, 1, 1, 2, 1], dtype=int64)

In [103]:
# Let's include Region as well

X_train, X_test, y_train, y_test = train_test_split(X[['post1906', 'thumbSty', 'region']],y, test_size=0.3, random_state=32)

In [120]:
dtree = DecisionTreeClassifier(criterion = 'entropy')
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f"The accuracy : {round(accuracy_score(y_test, y_pred),4)*100}%")
print(classification_report(y_test, y_pred))

[[ 8  2  0]
 [ 2 12  0]
 [ 0  4  0]]
The accuracy : 71.43%
              precision    recall  f1-score   support

           1       0.80      0.80      0.80        10
           2       0.67      0.86      0.75        14
           3       0.00      0.00      0.00         4

    accuracy                           0.71        28
   macro avg       0.49      0.55      0.52        28
weighted avg       0.62      0.71      0.66        28



C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Observation: Accuracy has improved upon inclusion of region

## Random Forest

First with REGION included

In [137]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=500)

In [146]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"The accuracy : {round(accuracy_score(y_test, y_pred),4)*100}%")

[[ 8  2  0]
 [ 2 12  0]
 [ 0  4  0]]
              precision    recall  f1-score   support

           1       0.80      0.80      0.80        10
           2       0.67      0.86      0.75        14
           3       0.00      0.00      0.00         4

    accuracy                           0.71        28
   macro avg       0.49      0.55      0.52        28
weighted avg       0.62      0.71      0.66        28

The accuracy : 71.43%


C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Observation: This is improvement in terms of removing overfitting. Precision and Recall are now more balanced and realistic** 

In [ ]:
# Without region

In [119]:
rf.fit(X_train.drop(['region'], axis = 1), y_train)
y_pred = rf.predict(X_test.drop(['region'], axis = 1))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"The accuracy : {round(accuracy_score(y_test, y_pred),4)*100}%")

[[10  0  0]
 [ 7  7  0]
 [ 0  4  0]]
              precision    recall  f1-score   support

           1       0.59      1.00      0.74        10
           2       0.64      0.50      0.56        14
           3       0.00      0.00      0.00         4

    accuracy                           0.61        28
   macro avg       0.41      0.50      0.43        28
weighted avg       0.53      0.61      0.54        28

The accuracy : 60.709999999999994%


C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python Folder\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Observation: No difference** 

In [158]:
accuracy = []

for i in range(100):
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    accuracy.append(accuracy_score(y_test, y_pred))

In [153]:
np.mean(accuracy)*100

59.28571428571425

In [155]:
np.min(accuracy)*100

57.14285714285714

In [156]:
np.max(accuracy)*100

60.71428571428571

In [159]:
print(f"Min accuracy: {np.min(accuracy)*100} | Mean accuracy: {np.mean(accuracy)*100} | Max accuracy: {np.max(accuracy)*100}")

Min accuracy: 60.71428571428571 | Mean accuracy: 66.60714285714285 | Max accuracy: 71.42857142857143
